## Omega and Xi

To implement Graph SLAM, a matrix and a vector (omega and xi, respectively) are introduced. The matrix is square and labelled with all the robot poses (xi) and all the landmarks (Li). Every time you make an observation, for example, as you move between two poses by some distance `dx` and can relate those two positions, you can represent this as a numerical relationship in these matrices.

Below you can see a matrix representation of omega and a vector representation of xi.

<img src='images/omega_xi.png' width=20% height=20% />


### Solving for x, L

To "solve" for all these poses and landmark positions, we can use linear algebra; all the positional values are in the vector `mu` which can be calculated as a product of the inverse of omega times xi.

---


### Quiz: Construct constraints for 3 motions and return `mu`

In the following example, you will complete the function call `mu_from_positions(-3, 5, 3)`, which takes in 3 robot poses/moves:
* initial pose: -3
* moves by 5
* moves by 3

In this function, you should construct the constraint matrices `omega` and `xi` and calculate `mu`. The final call should result in a `mu` of:
```
[[-3.0],
 [2.0],
 [5.0]]
 ```

## Constraint Updates

We will not consider landmark sensor measurements in this example, only robot poses.

#### Motion
When your robot moves by some amount `dx` update the constraint matrices as follows:
* Add `[[1, -1], [-1, 1]]` to omega at the indices for the intersection of `xt` and `xt+1`
* Add `-dx` and `dx` to xi at the rows for `xt` and `xt+1`

In [3]:
import numpy as np


def mu_from_positions(initial_pos, move1, move2):
    
    ## TODO: construct constraint matrices
    ## and add each position/motion constraint to them
    
    # Your code here
    omega = np.zeros([3,3])
    xi = np.zeros([3,1])
    
    # init pose
    omega[0][0] = 1
    xi[0][0] = initial_pos
    
    m_pose = np.array([[1,-1],
                       [-1,1]])
    
    omega[0:2,0:2] += m_pose
    xi[0:2,0] += np.array([-move1, move1])
    
    omega[1:3,1:3] += m_pose
    xi[1:3,0] += np.array([-move2, move2])
    
    
    # display final omega and xi
    print('Omega: \n', omega)
    print('\n')
    print('Xi: \n', xi)
    print('\n')
    
    ## TODO: calculate mu as the inverse of omega * xi
    ## recommended that you use: np.linalg.inv(np.matrix(omega)) to calculate the inverse
    mu = np.linalg.inv(np.matrix(omega))*np.array(xi)
    return mu


In [58]:
# call function and print out `mu`
mu = mu_from_positions(-3, 5, 3)
print('Mu: \n', mu)

Omega: 
 [[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]


Xi: 
 [[-8.]
 [ 2.]
 [ 3.]]


Mu: 
 [[-3.]
 [ 2.]
 [ 5.]]


### A try on finding the location

In [15]:
def mu_from_positions(initial_pos, move1, move2, dis0, dis1, dis2):
    omega = np.zeros([4,4])
    xi = np.zeros([4,1])
    
    # init pose
    omega[0][0] = 1
    xi[0][0] = initial_pos
    
    m_pose = np.array([[1,-1],
                       [-1,1]])
    
    omega[0:2,0:2] += m_pose
    xi[0:2,0] += np.array([-move1, move1])
    
    omega[1:3,1:3] += m_pose
    xi[1:3,0] += np.array([-move2, move2])
    
    l_pose = np.array([1,-1,-1,1])
    omega[[0,0,3,3],[0,3,0,3]] += l_pose
    omega[[1,1,3,3],[1,3,1,3]] += l_pose
    omega[[2,2,3,3],[2,3,2,3]] += l_pose
    
    xi[[0,3],0] += np.array([-dis0,dis0])
    xi[[1,3],0] += np.array([-dis1,dis1])
    xi[[2,3],0] += np.array([-dis2,dis2])
    
    
    # display final omega and xi
    print('Omega: \n', omega)
    print('\n')
    print('Xi: \n', xi)
    print('\n')
    
    ## TODO: calculate mu as the inverse of omega * xi
    ## recommended that you use: np.linalg.inv(np.matrix(omega)) to calculate the inverse
    mu = np.linalg.inv(np.matrix(omega))*np.array(xi)
    return mu

In [16]:
mu = mu_from_positions(-3, 5, 3, 10, 5, 2)
print('Mu: \n', mu)

Omega: 
 [[ 3. -1.  0. -1.]
 [-1.  3. -1. -1.]
 [ 0. -1.  2. -1.]
 [-1. -1. -1.  3.]]


Xi: 
 [[-18.]
 [ -3.]
 [  1.]
 [ 17.]]


Mu: 
 [[-3.]
 [ 2.]
 [ 5.]
 [ 7.]]


<span style='color:#f66;font-size:20px'> Well done
</span>